### ISSUE TITLE
Improvement: Fix short descriptions in "Putting Uptane to Work" section

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#105]
### Issue Summary

We need to add short descriptions for the items in the "Putting Uptane to Work" section on the homepage. Right now the text just says "short description of ..."

### Priority Level

Medium

### Related Information

<img width="1246" alt="image" src="https://github.com/uptane/uptane.github.io/assets/89217603/98ec8392-3227-454a-affd-20707c96a115">

**Comment by jhdalek55** [comment]
@hexsecs I am currently proofreading the site and noticed this as well. I'm proposing the following--
Uptane Standard
The set of requirements necessary for the secure implementation of the framework

Deployment Best Practices
Examples of best practices for setting up, operating, integrating, and adapting Uptane to work in a variety of situations.

PUREs
A vehicle for proposing an addition to or modification of the Uptane Standard.

POUFs
A mechanism to describe the protocols, operations, usage, and formats of an Uptane implementation.

**Comment by hexsecs** [comment]
@Mikerniker this one is related to #108 . Can I assign it to you as well?

**Comment by Mikerniker** [comment]
Hi @hexsecs , sure-->  although this is part of one of my questions in [#108](https://github.com/uptane/uptane.github.io/issues/108) regarding the location of the Home Page (since this also falls under the Home Page) and may be a .jsx file.

**Comment by hexsecs** [comment]
The relevant file is [static/puttingUptane/data.js](https://github.com/uptane/uptane.github.io/blob/uptane_docusaurus/static/puttingUptane/data.js)

**Comment by Mikerniker** [comment]
ok, I'll put it in the 2nd PR with the Home Page revisions. Thank you

**Comment by hexsecs** [comment]
fixed in #111
