### ISSUE TITLE
Other: SEO Optimization

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#107]
### Issue Summary

Add SEO optimization to our site...
https://docusaurus.io/docs/next/seo

**Comment by devilkiller-ag** [comment]
@hexsecs Should I try this?

**Comment by hexsecs** [comment]
> @hexsecs Should I try this?

@devilkiller-ag - I can assign to you.

**Comment by devilkiller-ag** [comment]
Is there any set of metadata keywords you already have that I should add to the `docusaurus.config.js` file. Or do I have to browse through whole site and add keywords of my choice?

**Comment by devilkiller-ag** [comment]
@hexsecs Can you check the PR to let me know if am I missing something?
