### ISSUE TITLE
Move Deployment considerations content to the website

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane.github.io#11]
This issue is just a housekeeping issue to track the work on moving the deployment considerations. Closes https://github.com/uptane/uptane-standard/issues/68.

**Comment by jhdalek55** [comment]
@tkfu ...do we still need to keep this open now that the deployment pages have been moved?

**Comment by patrickvacek** [comment]
Arguably this isn't done since the Standard still refers to the Google docs and the new versions are still in progress.

**Comment by jhdalek55** [comment]
Hmmm...good point. Maybe we should leave it for now.

**Comment by jhdalek55** [comment]
@tkfu On the last phone call it was agreed it was time to take the Deployment pages live. So perhaps its time to close this issue as well

**Comment by patrickvacek** [comment]
See https://github.com/uptane/uptane.github.io/pull/21, although I think that still isn't *actually* addressing the real issue here.

**Comment by tkfu** [comment]
Closed by #22.
