### ISSUE TITLE
Task: Get repository working from 'main' branch.

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#112]
- [x] Tag current `master` branch to archive state before merge.
- [x] Per generally accepted guidelines for git naming, rename '`master`' --> '`main`'.
- [x] Merge '`uptane_docusaurus`' into '`main`'
- [x] Fix CI workflows to point to '`main`' instead of '`uptane_docusaurus`'
- [x] Configure github to serve page from '`main`' branch.
- [x] Set default branch to '`main`'

**Comment by hexsecs** [comment]
Complete. Working now. For people working on the tickets, we may need to notify them to make pull requests to the 'main' branch.

**Comment by Abhijay007** [comment]
Phil I think as you have admin level access you now can directly change the
branch to the `main` for those PRs, I think there should be an option at
the top under every PR

**Comment by hexsecs** [comment]
@Abhijay007 - looks like I have the power! Thanks for pointing that out.
