### ISSUE TITLE
[Bug Report] - Argos CI Screenshots failing at `run yarn playwrite test` step

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#116]
### Describe the bug.

Run yarn playwright test
yarn run v1.22.19
$ /home/runner/work/uptane.github.io/uptane.github.io/node_modules/.bin/playwright test

Error: ENOENT: no such file or directory, open './screenshot.css'

   at argos/screenshot.spec.js:10

   8 | const sitemapPath = './build/sitemap.xml';
   9 | const stylesheetPath = './screenshot.css';
> 10 | const stylesheet = fs.readFileSync(stylesheetPath).toString();
     |                       ^
  11 |
  12 | // Wait for hydration, requires Docusaurus v2.[4](https://github.com/uptane/uptane.github.io/actions/runs/6695724126/job/18191913819#step:7:5).3+
  13 | // Docusaurus adds a <html data-has-hydrated="true"> once hydrated

    at Object.<anonymous> (/home/runner/work/uptane.github.io/uptane.github.io/argos/screenshot.spec.js:[10](https://github.com/uptane/uptane.github.io/actions/runs/6695724126/job/18191913819#step:7:11):23)

Error: No tests found

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Describe the steps to reproduce the behavior.

Happens every time `Argos CI Screenshots` CI workflow is run.

### Expected behavior.

It should run without issue.

### Operating environment

Ubuntu

**Comment by hexsecs** [comment]
@devilkiller-ag the workflow can't seem to find screenshot.css. Perhaps a path issue?

**Comment by devilkiller-ag** [comment]
Hi @hexsecs, I will check this out.

**Comment by devilkiller-ag** [comment]
Hi @hexsecs I solved this error. However, I noticed that for argos to perform screenshot test we need build of website. So its failing locally giving this error:
```bash
$yarn playwright test
yarn run v1.22.19
$ /home/devilkillerag/Documents/OpenSource/uptane-website/node_modules/.bin/playwright test
Error: ENOENT: no such file or directory, open './build/sitemap.xml'

   at argos/utils.js:7

   5 | // Docusaurus generates a build/sitemap.xml file for you!
   6 | export function extractSitemapPathnames(sitemapPath) {
>  7 |     const sitemap = fs.readFileSync(sitemapPath).toString();
     |                        ^
   8 |     const $ = cheerio.load(sitemap, { xmlMode: true });
   9 |     const urls = [];
  10 |     $('loc').each(function handleLoc() {

    at extractSitemapPathnames (/home/devilkillerag/Documents/OpenSource/uptane-website/argos/utils.js:7:24)
    at /home/devilkillerag/Documents/OpenSource/uptane-website/argos/screenshot.spec.js:30:46
    at Object.<anonymous> (/home/devilkillerag/Documents/OpenSource/uptane-website/argos/screenshot.spec.js:29:6)
Error: No tests found




error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hexsecs** [comment]
If you are doing it locally you can call a `yarn build` first.

**Comment by hexsecs** [comment]
To manually test the steps locally I ran...

```
yarn install
yarn playwright install
yarn playwright test
```
I was able to get it work successfully pass.
<img width="1094" alt="image" src="https://github.com/uptane/uptane.github.io/assets/89217603/d090f73f-b578-415a-834e-05849fef2aef">

**Comment by hexsecs** [comment]
@devilkiller-ag can you fix the path and submit a PR. For me, I got it working using the path `./argos/screenshot.css`

**Comment by hexsecs** [comment]
@devilkiller-ag I think your other PR commit trashed the yarn.lock file also. That might be part of the issue. So actually the steps should be...

```
rm yarn.lock
yarn install
yarn playwright install
yarn playwright test
```

**Comment by devilkiller-ag** [comment]
Yeah I resolved all issues. Before pushing I want to confirm that, do I need to put /screenshot created by running the teat to .gitignore file?
