### ISSUE TITLE
Other:  Add Youtube link to new Uptane site footer

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#119]
### Issue Summary

 Add the Uptane Youtube link to the new Uptane site footer, under the community section 
  
![image](https://github.com/uptane/uptane.github.io/assets/64387054/f14384cc-d908-4fd1-b8ca-7bc96c38c1e5)

here is the link to the channel: https://www.youtube.com/@Uptane

**Comment by tejas-raskar** [comment]
I would like to work on this issue

**Comment by Abhijay007** [comment]
sure @tejas-raskar go ahead

**Comment by tejas-raskar** [comment]
@Abhijay007 I have made the required changes. Please review
