### ISSUE TITLE
Other: Refactor site to move static sections out of the versioned /docs/ tree

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#124]
### Issue Summary

Really we should only version the "Standard" and "Deployment Best Practices" sections. Currently we have seperate versions for the "Learn More/* sections. Users should always be pointed to the latest version of these documents. They should be static and not part of the versioned docs components.

My expectation is that the Learn more section should not be versioned, and be found at the following URL tree...
https://uptane.github.io/learn-more

**Comment by Abhijay007** [comment]
we need to use multi-instance for this : https://docusaurus.io/docs/docs-multi-instance#versioned-and-unversioned-doc,  I will look into this after v3 migration
