### ISSUE TITLE
[Bug Report] - Missing best practices glossary section

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#133]
### Describe the bug.

Glossary section is missing from best practices page. Source file here...
https://github.com/uptane/deployment-considerations/blob/master/glossary.md

**Comment by Abhijay007** [comment]
"Hey @hexsecs, I believe we initially decided to remove the glossary section from the site since it seems to serve as nothing more than a table of contents, at least as far as I know. I'm not entirely certain about it. @jhdalek55, do you have any comments on this?

**Comment by jhdalek55** [comment]
No. @Abhijay007 It's not a table of contents. It provides the accepted definitions for key components of Uptane mentioned in the Standard and Deployment pages. It should be on the website and integrated into the printed versions of the Deployment Best Practices.

**Comment by hexsecs** [comment]
IMHO we should merge it in as section of the best practices.

**Comment by devilkiller-ag** [comment]
Can I work on this issue?

**Comment by Abhijay007** [comment]
> Can I work on this issue?

sure @devilkiller-ag go ahead
