### ISSUE TITLE
[Bug Report] - Merge in changes to adoptions into the current Uptane page

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#135]
### Describe the bug.

There were newer changes to the adoptions page that didn't make it over into the new site.
https://github.com/uptane/uptane.github.io/blob/362e7e9b92031d18c1afe2985f83c57637770c36/adoptions.md?plain=1

Merge in changes from here.

**Comment by devilkiller-ag** [comment]
Hi, Can I work on this issue?

**Comment by Abhijay007** [comment]
Ya ashmit go ahead
