### ISSUE TITLE
Proposal for Adding "Uptane Contributors" Section to the Website and Workflow Integration

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#160]
### Discussed in https://github.com/uptane/uptane.github.io/discussions/144

<div type='discussions-op-text'>

<sup>Originally posted by **Abhijay007** November 17, 2023</sup>
Hello Uptane community,

We are considering the addition of a new section on our website dedicated to "Uptane Contributors." Here's a preview of how it would appear:

Uptane Contributors

![image](https://github.com/uptane/uptane.github.io/assets/64387054/bdf3fd9a-42e6-479f-8167-6a0d4936d3d8)

To streamline the process, we are seeking a solution that automates triggers or workflows whenever a new contributor is added. Importantly, we aim to feature not only contributors to the "uptane website contributors" but also contributors from across the entire Uptane community projects on github.

If anyone is aware of an open-source solution that fits our requirements, please share your insights. As a reference, the Moja Global repository has implemented a similar feature on their community website. You can explore it here: [Moja Global Community](https://community.moja.global/) (scroll down to the "Contributors" section).  you can find the corresponding repository on GitHub: [Moja Global Community Website Repo](https://github.com/moja-global/community-website).

We appreciate any feedback or suggestions you may have on implementing a comparable solution for our community repository.</div>

**Comment by Abhijay007** [comment]
cc @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Hi @Abhijay007, will start working on it soon.
