### ISSUE TITLE
Feature Request: Add a Featured Blog/News Section 

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#167]
### Is your feature request related to a problem? Please describe.

So, as we have a few blogs on the Uptane site, we want to feature the three most recent ones on the main page of the site.

### Describe how you would like this problem to be resolved

Create a component as displayed below in the Figma design:

![image](https://github.com/uptane/uptane.github.io/assets/64387054/dd003420-4d43-4bf8-b467-f9948422345e)

This component should display the most recent blogs on the site along with their images and titles."

**Comment by hexsecs** [comment]
As we discussed in the friday website call, we should use this to feature the latest three blog articles.

**Comment by devilkiller-ag** [comment]
Seems interesting. Let me know if you want any help regarding this @Abhijay007.
