### ISSUE TITLE
Links to Deployment Considerations on Reference POUF page are dead

### ISSUE THREAD

**Issue by cwaldren** [uptane/uptane.github.io#23]
On https://uptane.github.io/reference_pouf.html, there are multiple dead links to [Deployment Considerations](https://uptane.github.io/deployment/introduction.html).

I haven't submitted a PR because I wasn't sure if [the existing page](https://uptane.github.io/deployment-considerations/index.html) was appropriate. For example: "For more about information about internal vehicle communication, see Deployment Considerations", but the new page doesn't actually contain this information.

**Comment by jhdalek55** [comment]
Thanks for calling this to our attention. We have been updating the links across the document, but I guess this was missed. We will see that this is fixed.

**Comment by jhdalek55** [comment]
@cwaldren I think we can now close this issue. Links to Deployment Best Practices, which is now the official title of this document, have been made consistent and have recently been reviewed and checked.  Once again thanks for pointing out the problem.

**Comment by pattivacek** [comment]
I don't know, I just did a quick check and several links point to https://uptane.github.io/deployment/introduction.html, which just redirects (non-automatically) to https://uptane.github.io/deployment-considerations/index.html, so maybe there's still some cleanup to do there.

**Comment by jhdalek55** [comment]
Ok. @cwaldren it appears we may have more work to do. @pattivacek is there anyway to globally check this? I'd rather not make publication "official."

**Comment by pattivacek** [comment]
Does this have anything to do with publishing the Standard and Deployment docs, though? This is just text on the website. I mean, it's still worth doing, but I don't think it's urgent.

**Comment by jhdalek55** [comment]
I guess not. I just looked again and I misread that we were talking about the Reference POUF page and not the Deployment document itself.

**Comment by jhdalek55** [comment]
Thanks for doing it. Might as well resolve this and get it off the repo.
