### ISSUE TITLE
Is Uptane still funded by DHS?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane.github.io#43]
In the footer on the website and in several other places, we claim Uptane **is** funded by DHS (present tense). Is this still true? If not, we need to clean out those references so we are not making false claims.

Whether we get a GSoC volunteer or not, I think we need to compile content-based issues that should be addressed sooner rather than later.

**Comment by JustinCappos** [comment]
It is not currently funded by DHS.  We should switch to past tense.

**Comment by jhdalek55** [comment]
Thats what I thought. I'll take care of this.

**Comment by jhdalek55** [comment]
Addressed via PR #46
