### ISSUE TITLE
Updating Uptane's website: What modifications are needed?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane.github.io#50]
The Uptane website at[ https://uptane.github.io/](https://uptane.github.io/) went live in January of 2019. Built on essentially the same structure as the website for its parent project, The Update Framework, it’s a serviceable website with quite a bit of information. Three years later, though, it’s apparent that the manner in which that material is arranged could use some serious modifications. In particular, we are concerned that someone new to Uptane might not be able to find the basic information it needs to consider adoption or integration.

We are looking to “deconstruct” the website in terms of layout and design to create a better information flow for users. While a cleaner and more contemporary look is desirable, we are mostly seeking a more logical arrangement of information. We also want to make sure that our site contains the _right type of information_ so we appreciate input on what should...or should not...be posted on this site.

We are inviting the community to either make comments on this thread, or to take a more active role by submitting pull requests to this repository.

**Comment by jhdalek55** [comment]
As it appears we will have a GSOC contributor assisting us with the website summer, I'm posting here some of the things I believe should be addressed. A lot of these things are content issues, which raises the question of whether the content should be prepared prior to the GSOC contributors arrival. Several of these things were on my "TODO" list for the month, so I would appreciate some feedback on whether or not I should move forward with the new copy.

**Comment by mnm678** [comment]
A couple of additional suggestions:
* Move "Press" under "Learn more", leaving room for the blog at the top level
* Put the Deployment Best Practices PDF in the same drop-down as the html pages
* We could re-frame "Why Uptane is needed" as a threat model
* Timeline should be updated
* Add a link to the Uptane Standard GitHub repository (or make it easier to find if it exists)

Overall, I'd love to see a re-think to how the sections are organized to make everything easier to find.

**Comment by jhdalek55** [comment]
I recommend we close this now.
