### ISSUE TITLE
Adding a "news box" to the home page

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane.github.io#54]
We currently have no way to spotlight news and events on the home page of the document. When we have a workshop scheduled or when we release a whitepaper, we should have a way to place these items right where the reader will see them when the site opens up. Is there some way to add a box to the home page that would make such items stand out?

**Comment by B1TSH3LL** [comment]
i would like to work on this issues.

**Comment by hexsecs** [comment]
@jhdalek55 @Abhijay007 Is this issue resolved now? I think the code is commented out, but I remember @Abhijay007 showing a news section of configurable size.

**Comment by Abhijay007** [comment]
> @jhdalek55 @Abhijay007 Is this issue resolved now? I think the code is commented out, but I remember @Abhijay007 showing a news section of configurable size.

ya @hexsecs It requires some work I will try to close this one soon, let's discuss this issue in the upcoming website call

**Comment by jhdalek55** [comment]
I think this is an important feature to have. We need a place on the home page to advertise upcoming workshops and the release of whitepapers.

**Comment by hexsecs** [comment]
> I think this is an important feature to have. We need a place on the home page to advertise upcoming workshops and the release of whitepapers.

I agree. We also need it to be easy for an uptane content moderator to add/remove news items.

**Comment by hexsecs** [comment]
Perhaps we close this issue in favor of blogs for right now? Current we are not posting enough content to keep a "news" box fresh.

**Comment by jhdalek55** [comment]
@hexsecs I agree. We really don't have anything to promote at this time. It would be great to focus more energy on putting together whitepapers and conferences so there is something to promote.

**Comment by hexsecs** [comment]
We are going to add a "latest blogs section". Any "news" we want to post can simply have a blog article about it.
