### ISSUE TITLE
Redundant content in People and Governance pages

### ISSUE THREAD

**Issue by pattivacek** [uptane/uptane.github.io#55]
While working on https://github.com/uptane/uptane.github.io/pull/53, I noticed that the [People](https://uptane.github.io/people.html) and [Governance](https://uptane.github.io/governance.html) pages have a lot of redundant material. Can we consider merging those pages, or otherwise removing the duplicate parts?

**Comment by jhdalek55** [comment]
Thanks @pattivacek.

**Comment by hexsecs** [comment]
I think this is a good idea. Additionally there are some people on the advisory group that don't regularly attend any more.

**Comment by hexsecs** [comment]
Closed by 1915c5f63564cddf295f4179eb4503329043dd33
