### ISSUE TITLE
Consistency when Deployment pages are open

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane.github.io#57]
Something strange is happening with the Deployment section of the  Uptane website. When you have one of the Deployment pages open, it changes the menu options on other sections of the website. For example, when I open the "Enhanced Security" page under the Deployment tab,  and then go back to the "Design Documents" tab, the only version of the Standard listed is V.1.1.0 and the PDF and HTML version of the Deployment pages are not listed at all. I'm assuming this may have something to do with the fact that the Deployment pages are not updated on uptane.github.io but on https://github.com/uptane/deployment-considerations. But, we need to rectify this discrepancy so all users of the site are seeing the same items.

**Comment by pattivacek** [comment]
For better or worse, this is how it was designed. Basically the deployment docs have a copy of the main website menu, except that the copy is now quite a bit out of date. Once upon a time I occasionally would try to synchronize the two, but I've not been able to keep up with that anymore.

I wonder if we might be able to solve this by including the main website repo as a submodule in the deployment docs? I'm not sure, someone with some time and git skills would need to investigate.

**Comment by jhdalek55** [comment]
@Abhijay007 @hexsecs  I think we can close this now given the new site design.

**Comment by Abhijay007** [comment]
> @Abhijay007 @hexsecs I think we can close this now given the new site design.

sure @jhdalek55
