### ISSUE TITLE
Add google analytics to uptane.github.io

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#58]
It looks like this is possible. 
https://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages

**Comment by B1TSH3LL** [comment]
i would like to work on this issue. please assign this to me.

**Comment by devilkiller-ag** [comment]
Is this issue still unresolved? I have done a similar thing for my portfolio website. So I can solve this.

**Comment by hexsecs** [comment]
@devilkiller-ag looking at the docusaurus documentation, it looks like it should be fairly straightforward. https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag

I can assign to you.

**Comment by devilkiller-ag** [comment]
@hexsecs Do I need to register our site to Google Analytics and get a new Tracking ID or is it done before? If it is done before can you please provide me with the Tracking ID or will it be stored as an environment variable?

**Comment by devilkiller-ag** [comment]
Okay, Should I add all the codes required; so that @hexsecs will only have to generate the Tracking ID and any of us can put it? Or should I wait till @hexsecs generates the ID and then do all the stuff in one go?

**Comment by hexsecs** [comment]
The measurement ID is G-G856J3S8ZG
