### ISSUE TITLE
Git Clone dropping error 

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#60]
### Describe the error you are facing 

For Windows, git clone is dropping an error, due to an invalid path or parameter in the `papers/Agenda_3:31_Uptane_Workshop.pdf` file 

![image](https://user-images.githubusercontent.com/64387054/230046810-208c882a-deeb-49eb-a511-45f9405f2055.png)

even if we download it directly from GitHub :  

![image](https://user-images.githubusercontent.com/64387054/230046937-ef82df67-0c60-4267-b659-a68e26640477.png)

Although it is working fine for the UNIX-based systems, I tried using ( WSL 2)

### Possible Solution 

Rename the file or remove the `:` from the file name

**Comment by Abhijay007** [comment]
cc : @jhdalek55

**Comment by hexsecs** [comment]
We should fix this by removing the ':' from the filename.

**Comment by Abhijay007** [comment]
fixed with site overhaul
