### ISSUE TITLE
Durable Links

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#67]
Create durable links to the latest standard version and best practices version.

Currently the latest version doesn't have it's own durable links. For example the current version is 2.1.0 but we don't have durable links for it.

Page | Link
------|------
Standard Latest (2.1.0) |  https://uptane.github.io/docs/standard/uptane-standard
Standard 2.1.0 |   https://uptane.github.io/docs/2.1.0/standard/uptane-standard  <-- To be added
Standard 2.0.0 |   https://uptane.github.io/docs/2.0.0/standard/uptane-standard 
.. | ..
Best Practices (2.1.0) | https://uptane.github.io/docs/deployment/best-practices
Best Practices 2.1.0 | https://uptane.github.io/docs/2.1.0/deployment/best-practices <-- To be added
Best Practices 2.0.0 | https://uptane.github.io/docs/2.0.0/deployment/best-practices

We need a way to reference the durable link to the standard (and best practices) of the latest version, so that a user can pin the version of the standard they want to reference INCLUDING whatever version is the latest.

**What I expect to work is...**
https://uptane.github.io/docs/standard/uptane-standard - points to whatever version is the latest. This content will change in the future, when a new version is released.
https://uptane.github.io/docs/2.1.0/standard/uptane-standard - points to a pinned version of 2.1.0.

**Comment by hexsecs** [comment]
The new website fixes this issue with the exception of the "latest" version. We will need to investigate how we can have both using docusaurus.

**Comment by Mikerniker** [comment]
Hi @hexsecs, is this what you had in mind for the durable links: 
![new_versiondocusaurus](https://github.com/uptane/uptane.github.io/assets/63586831/e591ec7f-cc70-4a82-8f68-1c9655aca800)
I'm not completely sure I understand, but let me know if this is the right direction, thank you

**Comment by hexsecs** [comment]
That looks a like a good automated way to do it. So we probably need to run `yarn docusaurus docs:version 2.1.0` to make a static version of the current spec.

**Comment by Mikerniker** [comment]
ok, can I try it out?

**Comment by hexsecs** [comment]
Sure. I assigned to you.

**Comment by Mikerniker** [comment]
Ok, thanks @hexsecs
