### ISSUE TITLE
Update Uptane logo

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#76]
We need up update the site with the new logo and icons in the https://github.com/uptane/uptane.github.io/tree/uptane_docusaurus branch. I will provide the SVG versions.

**Comment by hexsecs** [comment]
![uptane-horizontal-color-text-only](https://github.com/uptane/uptane.github.io/assets/89217603/c71854e0-2ca2-4834-a9b0-fc24fef4aed6)
![uptane-horizontal-color](https://github.com/uptane/uptane.github.io/assets/89217603/20899641-2806-4a82-a846-51ff1b165f57)

![uptane-icon-color](https://github.com/uptane/uptane.github.io/assets/89217603/94009d77-dc35-4a9f-87da-f315eb2a100b)

**Comment by Abhijay007** [comment]
@hexsecs I think logos are a bit distorted here on github

**Comment by hexsecs** [comment]
@Abhijay007, if I download the images, they render correctly on my computer. Perhaps it's an issue with the browser opening a svg directly?

**Comment by hexsecs** [comment]
We may want to export them into PNG files for use on the website.

**Comment by Abhijay007** [comment]
> We may want to export them into PNG files for use on the website.

no problem I will take care of this
