### ISSUE TITLE
Fix search functionality in new site

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#77]

**Comment by Abhijay007** [comment]
@hexsecs can you please apply for this: https://docsearch.algolia.com/apply/ for the search API and the index name, the API is required for performing search on the site it will generate the sitemap for uptane site, let me know when you get that I will implement the same

**Comment by hexsecs** [comment]
@Abhijay007 applied. I'll updated the ticket once they send the information. Our site application was approved

**Comment by hexsecs** [comment]
@Abhijay007 - I have the appId and apikey now.

**Comment by Abhijay007** [comment]
> @Abhijay007 - I have the appId and apikey now.

we also need the index name, you can create on using the dashboard

**Comment by hexsecs** [comment]
@Abhijay007 I emailed you the info (including index name).

**Comment by Abhijay007** [comment]
> @Abhijay007 I emailed you the info (including index name).

Thanks @hexsecs I will soon raise a PR for the same
