### ISSUE TITLE
Setup Issues template for the repo 

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#81]

**Comment by Mikerniker** [comment]
Hi @Abhijay007, just wanted to clarify if the instructions in the following link was what was needed to [create an issues templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository), if yes, can I be assigned to this? Also if you need both a template for the bug report and the feature request? Thank you

**Comment by Abhijay007** [comment]
> Hi @Abhijay007, just wanted to clarify if the instructions in the following link was what was needed to [create an issues templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository), if yes, can I be assigned to this? Also if you need both a template for the bug report and the feature request? Thank you

@Mikerniker you can do it via using YAML forms, you can refer to the issue templates from this repo here: https://github.com/open-horizon/open-horizon.github.io/tree/master/.github/ISSUE_TEMPLATE, we mainly need issue templates for bug- reports, features-requests, documentation, and for "others",  try to look into the attached resource and edit that according to our repo.

**Comment by Mikerniker** [comment]
Ok, can you confirm if this is correct: you need 4 YAML files (for bug reports, features, documentation, and others) and these should be stored in the `ISSUE_TEMPLATE` folder in the `.github` directory?

**Comment by Mikerniker** [comment]
Ok, can you confirm if this is correct: you need 3 YAML files (for bug reports, features, documentation and others) and these should be stored in the `ISSUE_TEMPLATE` folder in the `.github` directory?

**Comment by Abhijay007** [comment]
> Ok, can you confirm if this is correct: you need 3 YAML files (for bug reports, features, documentation and others) and these should be stored in the `ISSUE_TEMPLATE` folder in the `.github` directory?

ya but "others" is different form documentation so 4

**Comment by Mikerniker** [comment]
Ok, will try to set it up, thanks

**Comment by hexsecs** [comment]
Resolved by #95
