### ISSUE TITLE
Update/Revise The Readme File

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#85]
The Uptane project has recently adopted [Docusaurus](https://docusaurus.io/) as its primary platform for building its website. This transition marks an exciting step forward in our project's development. However, it has become evident that the existing readme file is no longer serving its intended purpose. It is crucial that we address this issue promptly.

The current readme file falls short in terms of clarity and effectiveness, which undermines our ability to effectively communicate and collaborate on our project. To rectify this, we are seeking your valuable input and suggestions to update and revamp our readme file. We believe that collective insights and ideas will help us create a more informative and user-friendly document.

We welcome any recommendations, be it for restructuring, content, or design elements that can improve the readability and usability of the readme file. Your contribution is essential in ensuring that our project is accessible and comprehensible to a wider audience.

PS: If you are interested in providing suggestions or assistance regarding the content and formatting of the readme file, please feel free to reach out to @jhdalek55.

**Comment by Mikerniker** [comment]
Hello  @jhdalek55 / @Abhijay007
Can I try to update the README.md by submitting an initial draft, following the steps given by @Abhijay007 from this [Pull Request #84](https://github.com/uptane/uptane.github.io/pull/84) to be able to run the Uptane (docusaurus site) locally ?

**Comment by Abhijay007** [comment]
> Hello @jhdalek55 / @Abhijay007 Can I try to update the README.md by submitting an initial draft, following the steps given by @Abhijay007 from this [Pull Request #84](https://github.com/uptane/uptane.github.io/pull/84) to be able to run the Uptane (docusaurus site) locally ?

ya sure @Mikerniker go ahead

**Comment by Aakashdeep-Srivastava** [comment]
kindly assign it to me

**Comment by Aakashdeep-Srivastava** [comment]
@Abhijay007  Please

**Comment by hexsecs** [comment]
I think this is already fixed in #88

**Comment by Abhijay007** [comment]
> I think this is already fixed in #88

I think there is some room for the improvements

**Comment by Abhijay007** [comment]
> @Abhijay007 Please

@Aakashdeep-Srivastava can you please suggest what we can improve in the existing readme file?

I think we can add : 

- community links to join discord, LinkedIn 
- stats around the repo

**Comment by hexsecs** [comment]
@Abhijay007 @Aakashdeep-Srivastava : Since @Mikerniker already submitted a pull request fixing this issue (at least a first revision of the new Readme) let's close this issue out as fixed by pull request #88. I'll open a new issue and assign to @Aakashdeep-Srivastava for improving the readme text with @Abhijay007 

Fixed by #88.
