### ISSUE TITLE
Add LinkedIn Page link to new Uptane site

### ISSUE THREAD

**Issue by Abhijay007** [uptane/uptane.github.io#93]
Here is the LinkedIn page link : 
https://www.linkedin.com/company/uptane/

**Comment by mit-anuj** [comment]
please assign me this

**Comment by Abhijay007** [comment]
sure @mit-anuj go ahead

**Comment by Abhijay007** [comment]
@mit-anuj here is the PR for reference  :  https://github.com/uptane/uptane.github.io/pull/90

**Comment by Abhijay007** [comment]
closed via #94
