### ISSUE TITLE
Improvements to the site README.md file

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#98]
The Uptane project has recently adopted [Docusaurus](https://docusaurus.io/) as its primary platform for building its website. This transition marks an exciting step forward in our project's development. 

The current readme file falls short in terms of clarity and effectiveness, which undermines our ability to effectively communicate and collaborate on our project. To rectify this, we are seeking your valuable input and suggestions to update and revamp our readme file. We believe that collective insights and ideas will help us create a more informative and user-friendly document.

We welcome any recommendations, be it for restructuring, content, or design elements that can improve the readability and usability of the readme file. Your contribution is essential in ensuring that our project is accessible and comprehensible to a wider audience.

PS: If you are interested in providing suggestions or assistance regarding the content and formatting of the readme file, please feel free to reach out to @jhdalek55 @hexsecs and @Abhijay007.

**Comment by hexsecs** [comment]
> @Aakashdeep-Srivastava can you please suggest what we can improve in the existing readme file?
> 
> I think we can add :
> 
> * community links to join discord, LinkedIn
> * stats around the repo

**Comment by Aakashdeep-Srivastava** [comment]
Yes I can do that: 
1)Community Links: Add links to Discord and LinkedIn for community engagement.
2)GitHub Stats: Include repository statistics (stars, forks) for transparency.
3)Visual Guides: Use screenshots or diagrams for clearer instructions.
4)Troubleshooting Section: Create a dedicated space for issue resolution.
5)Contributor Info: Offer guidance for contributing to the project.

**Comment by Aakashdeep-Srivastava** [comment]
Yes sure I was doing something like that only

**Comment by Abhijay007** [comment]
Hi @Aakashdeep-Srivastava any update on this one?

**Comment by hexsecs** [comment]
@Aakashdeep-Srivastava Any update on this issue? Shall we remove you as the assignee?

**Comment by hexsecs** [comment]
Awesome! Thanks @Aakashdeep-Srivastava

**Comment by Abhijay007** [comment]
@Aakashdeep-Srivastava any update on this ?

**Comment by shubhusion** [comment]
Kindly Assign this issue to me

**Comment by shubhusion** [comment]
@hexsecs 

![image](https://github.com/uptane/uptane.github.io/assets/96301987/c2e41456-6497-4cd7-8982-9cfd5d30cf6e)

I'd like to confirm the structure of the README. Will the preview provided above work? Let me know.

**Comment by hexsecs** [comment]
I like it! Can you propose a short description of the content you would like to see in each section? (Doesn't have to be super formal, just like 1-2 sentence description)

The aim is just to avoid you doing a bunch of work and then having to make a sweeping change or throw out work.

**Comment by shubhusion** [comment]
**Overview**
Brief description of the project, its purpose.

**Features**
List and explain the main features and functionality of the project.

**Repository Structure**
Overview of the project files and directory structure.

**Modules**
Description of the main modules, components, or libraries that make up the project.

**Getting Started**
Instructions on installing, configuring and running the project locally.

**Installation**
Steps for installing dependencies and requirements.

**Running**
Commands for running the project, server, tests, etc.

**Tests**
How to run included tests and examples.

**Roadmap**
Planned features and improvements for future releases.

**Contributing**
Guidelines for contributing to the project, submitting issues/bugs, and making pull requests.

**License**
Project license and copyright information.

**Acknowledgments**
Credits to dependencies, assets or contributors as needed.

**Comment by jhdalek55** [comment]
This looks good but do we want that much text on the Readme page, particularly when all this material  is already posted on the site? Much of this text ( Getting Started, Contributing, Overview, even Features, though we call it Design) is featured in other sections on the site.

**Comment by shubhusion** [comment]
> This looks good but do we want that much text on the Readme page, particularly when all this material  is already posted on the site? Much of this text ( Getting Started, Contributing, Overview, even Features, though we call it Design) is featured in other sections on the site.

If you don't want so much change , I can just make the Readme more Visually Appealing, Keeping the content unchanged.

**Comment by jhdalek55** [comment]
@shubhusion I'm just suggesting we not add text that we already have elsewhere. Some of the items on your list,such as running, test, and especially the roadmap, do not current exist and could be valuable additions.

**Comment by shubhusion** [comment]
Could you please assist by providing more details related to the content to be added inside the roadmap and running,test?

**Comment by jhdalek55** [comment]
@shubhusion we developed a timeline back in June of this year that set a series of goals for the coming few months. It included proposed dates for holding workshops, releasing versions of the standards, and publishing whitepapers. This list should be reviewed and approved though before we add it.
![Screen Shot 2023-11-11 at 11 29 41 AM](https://github.com/uptane/uptane.github.io/assets/14576223/70c958d9-ffe3-4c97-a435-06b3a5181a71)

The "test" section could document either completed tests or could propose best practices for doing such test. I don't believe we have anything like this on the site.

You had a proposed a "running" site. I assumed this might be troubleshooting tips for maintaining operations on the site. Perhaps you could explain what you had in mind when you proposed in?

@hexsecs @iramcdonald...Your thoughts?

**Comment by jhdalek55** [comment]
The timeline section was posted as possible content for the roadmap text

**Comment by hexsecs** [comment]
@jhdalek55 my view is that the readme should be focusing on the site itself and not necessarily the roadmap for the Uptane standard itself. So things like helping contributors get up and running and building the site are important.

**Comment by jhdalek55** [comment]
That is why I asked for your input.

**Comment by shubhusion** [comment]
> @shubhusion we developed a timeline back in June of this year that set a series of goals for the coming few months. It included proposed dates for holding workshops, releasing versions of the standards, and publishing whitepapers. This list should be reviewed and approved though before we add it. ![Screen Shot 2023-11-11 at 11 29 41 AM](https://user-images.githubusercontent.com/14576223/282254036-70c958d9-ffe3-4c97-a435-06b3a5181a71.png)
> 
> The "test" section could document either completed tests or could propose best practices for doing such test. I don't believe we have anything like this on the site.
> 
> You had a proposed a "running" site. I assumed this might be troubleshooting tips for maintaining operations on the site. Perhaps you could explain what you had in mind when you proposed in?
> 
> @hexsecs @iramcdonald...Your thoughts?

@jhdalek55 I proposed the "Running" Section for commands for running project , tests related to uptane framework but troubleshooting tips for maintaining operations on the site can also be added.

can you confirm whether Roadmap needs to be added or not?

**Comment by jhdalek55** [comment]
I believe @hexsecs is correct. There probably is a need for a Roadmap for the project, but the README is not the correct place.

**Comment by iramcdonald** [comment]
Hi,

I agree with Phil and Lois.  The Roadmap (which is now out-of-date) should
not be in the README.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by hexsecs** [comment]
@iramcdonald, @jhdalek55, et al.

We're talking about the README.md for the uptane.github.io (the website) repository *not* for the standard or best practices repositories. The readme here should be focused on helping contributors get the website running locally, building it, and how to contribute to the website. Thus, the readme contents should *not* be focused on the technical aspects of the uptane framework which we will call *website content*.

My opinion is that @shubhusion 's proposal is good, as long as we are following the above idea focusing on how to build and contribute to our uptane website.

(@iramcdonald and @jhdalek55 already know this part, but to explain to contributors...)
Uptane has two major aspects as related to the open source community: 

1. The uptane framework itself which includes content for the standard, best practices guides, and  other technical content...and 
2. The website which is also open source and contributor lead and developed. 

This repository is focused on the website thus anything in category 1) is essentially input content that may be hosted on the website.

**Comment by shubhusion** [comment]
@jhdalek55 @hexsecs let me know if below content works under Troubleshooting tips to be added under Running Section. 

# Troubleshooting Tips for Docusaurus Site Maintenance

## 1. Dependency Issues
- Keep Docusaurus and dependencies updated.
- Clear `node_modules` and reinstall dependencies if issues persist.

## 2. Build Failures
- Verify `docusaurus.config.js` for errors.
- Check browser console for build errors.

## 3. Plugin Conflicts
- Temporarily disable plugins to identify conflicts.
- Refer to plugin documentation for known issues.

## 4. Stale Content
- Regularly update documentation content.
- Check for and fix broken links.

## 5. Performance Optimization
- Optimize images and minify CSS/JavaScript.
- Enhance site performance for better user experience.

## 6. Responsive Design Issues
- Test across browsers and devices.
- Ensure mobile-friendly design.

## 7. Error Messages
- Review Docusaurus build and server logs.
- Search online forums for solutions.

## 8. Backup and Version Control
- Backup regularly, especially before major updates.
- Use version control (e.g., Git) for tracking changes.

Always refer to Docusaurus documentation and community resources for specific guidance, and test changes in a staging environment before applying them to production.

**Comment by hexsecs** [comment]
> @jhdalek55 @hexsecs let me know if below content works under Troubleshooting tips to be added under Running Section.
> 
> # Troubleshooting Tips for Uptane Site Maintenance
> ## 1. Dependency Issues
> * Keep Docusaurus and dependencies updated.
> * Clear `node_modules` and reinstall dependencies if issues persist.
> 
> ## 2. Build Failures
> * Verify `docusaurus.config.js` for errors.
> * Check browser console for build errors.
> 
> ## 3. Plugin Conflicts
> * Temporarily disable plugins to identify conflicts.
> * Refer to plugin documentation for known issues.
> 
> ## 4. Stale Content
> * Regularly update documentation content.
> * Check for and fix broken links.
> 
> ## 5. Performance Optimization
> * Optimize images and minify CSS/JavaScript.
> * Enhance site performance for better user experience.
> 
> ## 6. Responsive Design Issues
> * Test across browsers and devices.
> * Ensure mobile-friendly design.
> 
> ## 7. Error Messages
> * Review Docusaurus build and server logs.
> * Search online forums for solutions.
> 
> ## 8. Backup and Version Control
> * Backup regularly, especially before major updates.
> * Use version control (e.g., Git) for tracking changes.
> 
> Always refer to Docusaurus documentation and community resources for specific guidance, and test changes in a staging environment before applying them to production.

This looks good. For the Backup and version control section. I think we should only recommend using git. A good resource for how to contribute is here. https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by jhdalek55** [comment]
@shubhusion This all looks good to me.

**Comment by shubhusion** [comment]
@hexsecs @jhdalek55 can you provide me Discord server id
