### ISSUE TITLE
Create CI Workflow for visual regression testing

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#99]
The docusaurus site has an interesting suggestion for setting up an automated visual regression testing workflow. See here..
https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing

This might be something we want to add.

**Comment by devilkiller-ag** [comment]
Hi @hexsecs I can do this!

**Comment by hexsecs** [comment]
@devilkiller-ag - Awesome! I'll assign to you.

**Comment by devilkiller-ag** [comment]
@hexsecs Kindly check the PR I have created

**Comment by hexsecs** [comment]
> @hexsecs Kindly check the PR I have created

Thanks! We'll take a look!
